version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_ROOT_PASSWORD=${PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - /mysql_volume:/var/lib/mysql

  innoter_service:
    build: .
    container_name: "innoter_service"
    networks:
      - usersmanagementservice_default
    ports:
      - "8000:8000"
    environment:
      - PASS=${PASS}
      - NAME=${NAME}
      - BUCKET_NAME=${BUCKET_NAME}
      - MYSQL_HOST=mysql_db
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - RABBITMQ_HOST=rabbitmq_manage
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${HS256}
      - ACCESS_EXP=${ACCESS_EXP}
      - REFRESH_EXP=${REFRESH_EXP}

networks:
  usersmanagementservice_default:
    external: true
